// Chapter 21/chap-21/micro-frontend/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'micro-frontend';
  message?: string;

  @HostListener('window:message', ['$event']) onPostMessage(event: any) {
    const eventData = event.data;
    if (eventData && eventData.type === "SET_MESSAGE") {
      const data = eventData.data;
      this.message = data.message;
    }
  }

  sendMessage = () => {
    const iframe = document?.getElementById('react_app') as HTMLIFrameElement;
    iframe?.contentWindow?.postMessage({ type: 'SET_MESSAGE', data: { message: 'Hi, from Angular app!' } }, '*');
  }
}
<div>
  <h1>This is Angular app</h1>
  <h2>Message received: {{ message }}</h2>
  <button (click)="sendMessage()">Send Message</button>
  <iframe id="react_app" src="http://localhost:3000" width="100%" height="100%" frameborder="1"></iframe>
</div>

// Chapter 21/chap-21/react-app/src/App.js
import './App.css';
import { useEffect, useState } from 'react';

function App() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    window.addEventListener(
      "message",
      (event) => {
        const eventData = event.data;
        if (eventData && eventData.type === "SET_MESSAGE") {
          const data = eventData.data;
          setMessage(data.message);
        }
      },
      false,
    );
  }, []);

  const sendMessage = () => {
    const message = "Hello from React app!";
    window.parent.postMessage(
      {
        type: "SET_MESSAGE",
        data: { message },
      },
      "*",
    );
  }

  return (
    <div className="App">
      <h1>This is React app</h1>
      <h2>Message received: { message }</h2>
      <button onClick={sendMessage}>Send Message</button>
    </div>
  );
}

export default App;
